# Generated by Django 5.2.7 on 2025-10-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Apellido_Paterno', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('Apellido_Materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, verbose_name='Sexo')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('Direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('Comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
