# Generated by Django 5.2.7 on 2025-10-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, unique=True, verbose_name='Número de Ficha')),
                ('Edad', models.IntegerField(verbose_name='Edad')),
                ('Estado_civil', models.CharField(choices=[('Soltera', 'Soltera'), ('Casada', 'Casada'), ('Divorciada', 'Divorciada'), ('Viuda', 'Viuda'), ('Conviviente', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('Previcion', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('Privado', 'Privado'), ('Otro', 'Otro')], max_length=20, verbose_name='Previsión')),
                ('embarazos_previos', models.IntegerField(default=0, verbose_name='Embarazos Previos')),
                ('partos_previos', models.IntegerField(default=0, verbose_name='Partos Previos')),
                ('abortos_previos', models.IntegerField(default=0, verbose_name='Abortos Previos')),
                ('hipertension', models.BooleanField(default=False, verbose_name='Hipertensión')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('diabetes_gestacional', models.BooleanField(default=False, verbose_name='Diabetes Gestacional')),
                ('otras_patologias', models.TextField(blank=True, null=True, verbose_name='Otras Patologías')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='core.persona')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ControlPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateField(verbose_name='Fecha de Control')),
                ('semanas_gestacion', models.IntegerField(verbose_name='Semanas de Gestación')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('presion', models.CharField(blank=True, max_length=20, verbose_name='Presión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Control Prenatal',
                'verbose_name_plural': 'Controles Prenatales',
                'ordering': ['-fecha_control'],
            },
        ),
    ]
