# Generated by Django 5.2.7 on 2025-10-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Atención del Parto', 'Atención del Parto'), ('Control Prenatal', 'Control Prenatal'), ('Neonatología', 'Neonatología')], max_length=100, verbose_name='Especialidad')),
                ('Registro_medico', models.CharField(max_length=100, unique=True, verbose_name='Registro')),
                ('Años_experiencia', models.IntegerField(verbose_name='Años de Experiencia')),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='Turno')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrona', to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Matrona',
                'verbose_name_plural': 'Matronas',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Obstetricia General', 'Obstetricia General'), ('Ginecología', 'Ginecología'), ('Medicina Materno Fetal', 'Medicina Materno Fetal')], max_length=100, verbose_name='Especialidad')),
                ('Registro_medico', models.CharField(max_length=100, unique=True, verbose_name='Registro Médico')),
                ('Años_experiencia', models.IntegerField(verbose_name='Años de Experiencia')),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='Turno')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Tens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(choices=[('Preparto', 'Preparto'), ('Parto', 'Parto'), ('Puerperio', 'Puerperio'), ('Neonatología', 'Neonatología')], max_length=100, verbose_name='Nivel')),
                ('Años_experiencia', models.IntegerField(verbose_name='Años de Experiencia')),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='Turno')),
                ('Certificaciones', models.CharField(choices=[('SVB', 'Soporte Vital Básico'), ('Parto Normal', 'Certificación en Parto Normal')], max_length=100, verbose_name='Certificaciones')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tens', to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'TENS',
                'verbose_name_plural': 'TENS',
            },
        ),
    ]
