# Generated by Django 5.2.7 on 2025-10-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsión', models.CharField(choices=[('fonasa', 'FONASA'), ('isapre', 'ISAPRE'), ('privado', 'Privado'), ('otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_admision', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admision', to='core.persona')),
            ],
            options={
                'verbose_name': 'Admisión',
                'verbose_name_plural': 'Admisiones',
                'ordering': ['-fecha_admision'],
            },
        ),
    ]
